### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by Machinimo** [iobroker-community-adapters/info#37]
**npm:** 
machinimo

**chat:** 
Discord: Machinima#0461

**Comment by Apollon77** [comment]
Hey, which adapters you want to bring in or maintain?

**Comment by Machinimo** [comment]
I want to maintain hue-extended. I'm using this adapter in my production environment but there are several issues (e.g. wrong types) I want to fix and to bring the adapter up to date

**Comment by Apollon77** [comment]
Can we please start with a "normal" PR approach? You are relatively new in the developer community and adding you as member would grant you many rights ... So we can also offer support in form of reviews.

Other alternative would be grant you write access to just hue-extended as first step.

What do yoiu think?

**Comment by Machinimo** [comment]
Hi, starting with the PR approach is not a problem for me. Despite I'm new in the Github developer community I'm a professional C# developer who is also gaining experience in developing Node.js applications (currently only for my company).

**Comment by Apollon77** [comment]
@Machinimo I do not want to say that you are a bad developer (and never would!) it is just about that you are new in our community and giving you access to >100 repositories "out of nowhere" is also kind of a risk. So we mainly do this for "Known" developers. I hope this is understandable.

Thank you for starting with PR. Just mention me if you need a review. I'm sure we can invite you to the community later too!

PS: If you like also joind telegram or discord developer groups

**Comment by mcm1957** [comment]
@Machinimo 

How to proceed here?
I did not notice any PR from you.

The hue-extended adapter has been deprecated in the meantime as the hue adapter has been refurbiished and is fully maintained. If you still want to update hue-extended please let us know. Otherwise I will close this issue for now.

But I want to ensure that you and any other dev who can and wants to spent time for the ioBroker project is welcome at any time. So feel free to request an addition of a new adapter at iobroker.repositories or contact us if you want to contribute to an existing community adapter.

**Comment by mcm1957** [comment]
closed due to inactivity

Please feel free to contact us again if you would like to contribute.
@Apollon77 FYI
