### ISSUE TITLE
Please add me as a member - Schmakus / Doorbird, Hue

### ISSUE THREAD

**Issue by Schmakus** [iobroker-community-adapters/info#44]
**npm:** 
Schmakus

**chat:** 
Schmakus

grant write access to Doorbird and Hue Adapter.

**Comment by mcm1957** [comment]
I've enabled write access to the repo ioBroker.doorbird. You should be able to work directly in this repository and perform almost all operations except admin tasks like adding new users or deleting the repository. If any desired operation is not possible, please let me know, I'll check.

Please check und let me / us know if its ok.

In addition please contact me (i.e. telegram mcm1957) before doing you first release operation. I would like to explain the usage of alcazones releasescript if required if you are not familar with alcalzone/release-script.

In regard of hue adapter, I did not reach @foxriver76 yet. Do you know, that this adapter has been migrated to typescript? Are you familar with typescript? Your last open PR is still javascritp and so - I guess - could not be used any longer. Please contact @foxriver76 and ask him whether ist ok for him that you have direct access or if he prefers to merge PRs.  So he could either grant write access for the repository for you by himself or post a short ok here so that I can continue and add write access for you.


Welcome and THANK YOU for spending time and know how to support this adapter.

**Comment by foxriver76** [comment]
I prefer PRs für Hue, it’s always better to have a second pair of eyes whenever possible
