### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by peterbaumert** [iobroker-community-adapters/info#59]
**npm:** 
peterbaumert

**chat:** 
discord: pete_ba

**Comment by mcm1957** [comment]
Which adapter do you plan to maintain?

**Comment by peterbaumert** [comment]
I want to transfer my adapter to the community since I have no time anymore to maintain them. Like this at least someone can pick it up. Its unifi-protect and vofo-speedtest

**Comment by mcm1957** [comment]
If you (at this time) only want to transfer you adapter I would suggest that I do the transfer and adapt the urls to meet community. I would add you to the repo of you adapter (if needed after the transfer) so that you could work on it if you like.

If this is an option, please consider transferring the to repositories to me (mcm1957). I would transfer them to community immidiatly afterwards. So we do not need to add you to community at gh and npm if you do not plan to maintain adaoters in theis area in the near future.

But you are VERY welcome if you have time to maintain any adapoter in the pool. So please let us know if you have time to do something here.

**Comment by mcm1957** [comment]
@Apollon77 
Just for Info about the topic

**Comment by mcm1957** [comment]
Please send an invite at npm too so that I can add npm package to community orga

**Comment by mcm1957** [comment]
Adapter Repos have been transferred.
![image](https://github.com/iobroker-community-adapters/info/assets/28575778/6a4286ea-c387-4875-a2c0-48d8c6797d5c)

According to quick check you should have stoill write access.

Please let me know if you miss any right or if you wa nt to fully work at any community adapters infuture.
THANKS a lot for you work and the offer to transfer the adapters.

I will close here - hope this is ok for you
